polar_log_weight:
  description: Log a weight reading to Polar Flow.
  fields:
    date:
      description: The date the weight reading was taken, in the format yyyy-mm-dd.
      example: '2019-10-14'
    weight:
      description: The weight value to push (in whatever units is configured for your Polar Flow account).
      example: 163.2